ci: update pre-push hook

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -19,6 +19,19 @@ printError() {
 
 printMessage "Running local Lemonade pre-push hook."
 
+printMessage "Auto formatting code ..."
+
+# Run dart format
+dart format .
+
+# Check if there are any dart analyze issues
+analyze_output=$(dart analyze 2>&1)
+if [[ "$analyze_output" != *"No issues found!"* ]]; then
+    printError "Error in dart analysis. Aborting commit."
+	echo -e "Failed files:\n$analyze_output"
+    exit 1
+fi
+
 if [[ `git status --porcelain` ]]; then
     printError "This script needs to run against committed code only. Please commit or stash you changes."
     exit 1
